dbConfig:
    dbConfigFile: testnet/data/plutus-pab.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: True
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 10

walletServerConfig:
  tag: LocalWalletConfig
  walletSettings:
    baseUrl: http://localhost:8090

nodeServerConfig:
  pscSocketPath: testnet/node.sock
  pscBaseUrl: "localhost"
  pscKeptBlocks: 2160
  pscNetworkId: "1097911063" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1594369216000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  pscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  pscInitialTxWallets: []
  pscNodeMode: AlonzoNode

chainIndexConfig:
  ciBaseUrl: http://localhost:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084
  spWallet:
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: 0
  pabResumeFrom:
    # { "tag" : "PointAtGenesis" }
    { "tag" : "Point"
    , "pointBlockId" : "397d8795ac2b092aaa82369ac4367836a1180b87943933f8ee37c179be802221"
    , "pointSlot" : { "getSlot" : 56792484 }
    }

# Optional EKG Server Config
# ----
# monitoringConfig:
#   monitoringPort: 9090
